# Generated by Django 4.1.1 on 2022-11-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_whishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Whishlist',
        ),
    ]
